# Generated by Django 5.0.1 on 2024-02-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=25)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Select gender', max_length=20)),
                ('date_employed', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=25)),
                ('course_code', models.CharField(max_length=25)),
                ('dept_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.department')),
            ],
        ),
        migrations.CreateModel(
            name='CourseUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=25)),
                ('unit_code', models.CharField(max_length=25)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.department')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.staff')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('student_reg_no', models.CharField(max_length=25, unique=True)),
                ('student_email', models.EmailField(max_length=25)),
                ('student_phone', models.CharField(max_length=25)),
                ('reg_date', models.DateField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.courses')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.department')),
            ],
        ),
    ]
